apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: server:5432
    database: test_automation
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true

